version: '3.8'

services:
  db:
    container_name: mysqldb
    image: mysql:latest
    restart: always
    env_file:
      - ./.env
    ports:
      - 3306:3306
    volumes:
      - ./mysqldb-data:/var/lib/mysql
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql